#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DayMax.Resource", IsApplication=true)]

namespace DayMax
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::DayMax.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::DayMax.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::DayMax.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::DayMax.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::DayMax.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::DayMax.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::DayMax.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::DayMax.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::DayMax.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::DayMax.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::DayMax.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::DayMax.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::DayMax.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::DayMax.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::DayMax.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::DayMax.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::DayMax.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::DayMax.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::DayMax.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::DayMax.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::DayMax.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::DayMax.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::DayMax.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01001e
			public const int bottomEdgeSwipeOffset = 2130771998;
			
			// aapt resource value: 0x7f01000b
			public const int civ_border_color = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int civ_border_overlay = 2130771980;
			
			// aapt resource value: 0x7f01000a
			public const int civ_border_width = 2130771978;
			
			// aapt resource value: 0x7f01000d
			public const int civ_fill_color = 2130771981;
			
			// aapt resource value: 0x7f010020
			public const int clickToClose = 2130772000;
			
			// aapt resource value: 0x7f01001a
			public const int drag_edge = 2130771994;
			
			// aapt resource value: 0x7f010006
			public const int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int fab_colorNormal = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int fab_colorPressed = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fab_shadow = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int fab_size = 2130771977;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f01001b
			public const int leftEdgeSwipeOffset = 2130771995;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f01001c
			public const int rightEdgeSwipeOffset = 2130771996;
			
			// aapt resource value: 0x7f01001f
			public const int show_mode = 2130771999;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f010016
			public const int swipeActionLeft = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int swipeActionRight = 2130771991;
			
			// aapt resource value: 0x7f01000f
			public const int swipeAnimationTime = 2130771983;
			
			// aapt resource value: 0x7f010014
			public const int swipeBackView = 2130771988;
			
			// aapt resource value: 0x7f010012
			public const int swipeCloseAllItemsWhenMoveList = 2130771986;
			
			// aapt resource value: 0x7f010018
			public const int swipeDrawableChecked = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int swipeDrawableUnchecked = 2130771993;
			
			// aapt resource value: 0x7f010013
			public const int swipeFrontView = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int swipeMode = 2130771989;
			
			// aapt resource value: 0x7f010010
			public const int swipeOffsetLeft = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int swipeOffsetRight = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int swipeOpenOnLongPress = 2130771982;
			
			// aapt resource value: 0x7f01001d
			public const int topEdgeSwipeOffset = 2130771997;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int BG = 2131099649;
			
			// aapt resource value: 0x7f06000a
			public const int BlueInvestRect = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int BlueInvestText = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int ConvertColor = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int DarkGreen = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int GreenColor = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int LightGreen = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int RedColor = 2131099657;
			
			// aapt resource value: 0x7f060003
			public const int TableLineColor = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int TextColor = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int TopRowColor = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int fab_material_blue_500 = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040007
			public const int fab_elevation_lollipop = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int fab_scroll_threshold = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int fab_shadow_size = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int fab_size_mini = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int fab_size_normal = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Assets = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_with_shadow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Bills = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int business = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cashFlow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DayMax = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Default_Purse_Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Done = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Edit = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int fab_shadow = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int fab_shadow_mini = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int green_backdround_with_shadow = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int home = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int icon_sprite_min = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int invest_graph1 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int invest_graph2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int invest_graph3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int invest_graph4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int invest_graph5 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Investment = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Loans = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int logo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int More = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int None = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int profile_img = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Remove = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int rounded_button = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int rounded_edittext = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int splash_screen = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int stroke = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tmp_graph1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tmp_graph2 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tmp_graph3 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tmp_graph4 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tmp_graph5 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int white_background_with_shadow = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050078
			public const int CheckBox1ComissionMoney = 2131034232;
			
			// aapt resource value: 0x7f050077
			public const int CheckBox1ComissionPercents = 2131034231;
			
			// aapt resource value: 0x7f05007d
			public const int CheckBox2ComissionMoney = 2131034237;
			
			// aapt resource value: 0x7f05007c
			public const int CheckBox2ComissionPercents = 2131034236;
			
			// aapt resource value: 0x7f050039
			public const int FlyOutContainer = 2131034169;
			
			// aapt resource value: 0x7f05000e
			public const int FlyOutContent = 2131034126;
			
			// aapt resource value: 0x7f0500bd
			public const int FlyOutMenu = 2131034301;
			
			// aapt resource value: 0x7f050098
			public const int Linear = 2131034264;
			
			// aapt resource value: 0x7f0500c9
			public const int LinearAssets = 2131034313;
			
			// aapt resource value: 0x7f0500cc
			public const int LinearBills = 2131034316;
			
			// aapt resource value: 0x7f0500d0
			public const int LinearBusiness = 2131034320;
			
			// aapt resource value: 0x7f0500c2
			public const int LinearCashFlow = 2131034306;
			
			// aapt resource value: 0x7f0500d6
			public const int LinearDayMax = 2131034326;
			
			// aapt resource value: 0x7f0500bf
			public const int LinearHome = 2131034303;
			
			// aapt resource value: 0x7f0500d3
			public const int LinearInvestment = 2131034323;
			
			// aapt resource value: 0x7f0500c6
			public const int LinearLoans = 2131034310;
			
			// aapt resource value: 0x7f05009a
			public const int LinearTable = 2131034266;
			
			// aapt resource value: 0x7f05001c
			public const int Linqq = 2131034140;
			
			// aapt resource value: 0x7f0500b3
			public const int LoansAll = 2131034291;
			
			// aapt resource value: 0x7f0500b7
			public const int LoansCreditors = 2131034295;
			
			// aapt resource value: 0x7f0500b5
			public const int LoansDebitors = 2131034293;
			
			// aapt resource value: 0x7f05004c
			public const int MenuButton = 2131034188;
			
			// aapt resource value: 0x7f0500e3
			public const int MoreButton = 2131034339;
			
			// aapt resource value: 0x7f050075
			public const int Percent1 = 2131034229;
			
			// aapt resource value: 0x7f05007b
			public const int Percent2 = 2131034235;
			
			// aapt resource value: 0x7f05006e
			public const int Radio_CommisionToAccount1 = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int Radio_CommisionToAccount2 = 2131034223;
			
			// aapt resource value: 0x7f05001f
			public const int ShowPurse = 2131034143;
			
			// aapt resource value: 0x7f05004f
			public const int analogClock1 = 2131034191;
			
			// aapt resource value: 0x7f05000f
			public const int assetsaddviewitemslayout = 2131034127;
			
			// aapt resource value: 0x7f050036
			public const int assetshistorylayout = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int assetshistoryscroll = 2131034165;
			
			// aapt resource value: 0x7f050038
			public const int assetsmainlayout = 2131034168;
			
			// aapt resource value: 0x7f0500e4
			public const int backbutton = 2131034340;
			
			// aapt resource value: 0x7f05003a
			public const int billsmainlayout = 2131034170;
			
			// aapt resource value: 0x7f050003
			public const int both = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int bottom = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int btnCancel = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int btnOK = 2131034130;
			
			// aapt resource value: 0x7f05003b
			public const int businessmainlayout = 2131034171;
			
			// aapt resource value: 0x7f050051
			public const int calendarView1 = 2131034193;
			
			// aapt resource value: 0x7f050014
			public const int cashflowinsertframe = 2131034132;
			
			// aapt resource value: 0x7f050042
			public const int cashflowmainlayout = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int cashflowscroll = 2131034177;
			
			// aapt resource value: 0x7f050007
			public const int choice = 2131034119;
			
			// aapt resource value: 0x7f05005e
			public const int daymaxmainlayout = 2131034206;
			
			// aapt resource value: 0x7f050008
			public const int dismiss = 2131034120;
			
			// aapt resource value: 0x7f050044
			public const int earningmainlayout = 2131034180;
			
			// aapt resource value: 0x7f050043
			public const int earningscroll = 2131034179;
			
			// aapt resource value: 0x7f050045
			public const int expencescroll = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int expensesmainlayout = 2131034182;
			
			// aapt resource value: 0x7f05004a
			public const int frameLayout1 = 2131034186;
			
			// aapt resource value: 0x7f050054
			public const int iGraph1 = 2131034196;
			
			// aapt resource value: 0x7f05005d
			public const int iGraph10 = 2131034205;
			
			// aapt resource value: 0x7f050055
			public const int iGraph2 = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int iGraph3 = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int iGraph4 = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int iGraph5 = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int iGraph6 = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int iGraph7 = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int iGraph8 = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int iGraph9 = 2131034204;
			
			// aapt resource value: 0x7f0500d8
			public const int imagePurse = 2131034328;
			
			// aapt resource value: 0x7f05004d
			public const int imageView1 = 2131034189;
			
			// aapt resource value: 0x7f0500cd
			public const int imageView10 = 2131034317;
			
			// aapt resource value: 0x7f0500d1
			public const int imageView11 = 2131034321;
			
			// aapt resource value: 0x7f0500d4
			public const int imageView12 = 2131034324;
			
			// aapt resource value: 0x7f0500c0
			public const int imageView13 = 2131034304;
			
			// aapt resource value: 0x7f05009b
			public const int imageView2 = 2131034267;
			
			// aapt resource value: 0x7f0500c3
			public const int imageView5 = 2131034307;
			
			// aapt resource value: 0x7f0500c7
			public const int imageView8 = 2131034311;
			
			// aapt resource value: 0x7f0500ca
			public const int imageView9 = 2131034314;
			
			// aapt resource value: 0x7f050080
			public const int insertpursemainframe = 2131034240;
			
			// aapt resource value: 0x7f050082
			public const int investmentitemmainlayout = 2131034242;
			
			// aapt resource value: 0x7f0500aa
			public const int investmentmainlayout = 2131034282;
			
			// aapt resource value: 0x7f0500e6
			public const int item1 = 2131034342;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f05006a
			public const int lSumm_Send_Resend = 2131034218;
			
			// aapt resource value: 0x7f050070
			public const int lWith_Commission = 2131034224;
			
			// aapt resource value: 0x7f05000c
			public const int lay_down = 2131034124;
			
			// aapt resource value: 0x7f05006c
			public const int layouttmp = 2131034220;
			
			// aapt resource value: 0x7f050072
			public const int layouttmp1 = 2131034226;
			
			// aapt resource value: 0x7f050004
			public const int left = 2131034116;
			
			// aapt resource value: 0x7f05007e
			public const int linear = 2131034238;
			
			// aapt resource value: 0x7f05007f
			public const int linear1 = 2131034239;
			
			// aapt resource value: 0x7f05004b
			public const int linearLayout1 = 2131034187;
			
			// aapt resource value: 0x7f050031
			public const int linearLayout10 = 2131034161;
			
			// aapt resource value: 0x7f050025
			public const int linearLayout11 = 2131034149;
			
			// aapt resource value: 0x7f050037
			public const int linearLayout2 = 2131034167;
			
			// aapt resource value: 0x7f050026
			public const int linearLayout3 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int linearLayout4 = 2131034152;
			
			// aapt resource value: 0x7f050027
			public const int linearLayout5 = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int linearLayout6 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int linearLayout7 = 2131034156;
			
			// aapt resource value: 0x7f05002e
			public const int linearLayout8 = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int linearLayout9 = 2131034159;
			
			// aapt resource value: 0x7f0500a9
			public const int linearLayoutCash = 2131034281;
			
			// aapt resource value: 0x7f050083
			public const int linearLayoutMain = 2131034243;
			
			// aapt resource value: 0x7f05004e
			public const int linearLayoutbuf = 2131034190;
			
			// aapt resource value: 0x7f050084
			public const int linearStart = 2131034244;
			
			// aapt resource value: 0x7f05001b
			public const int linpurse = 2131034139;
			
			// aapt resource value: 0x7f0500b8
			public const int loanscreditorslayout = 2131034296;
			
			// aapt resource value: 0x7f0500b6
			public const int loansdebitorlayout = 2131034294;
			
			// aapt resource value: 0x7f0500b1
			public const int loanshistorylayout = 2131034289;
			
			// aapt resource value: 0x7f0500b0
			public const int loanshistoryscroll = 2131034288;
			
			// aapt resource value: 0x7f050063
			public const int loansinsertframe = 2131034211;
			
			// aapt resource value: 0x7f0500b4
			public const int loansmainlayout = 2131034292;
			
			// aapt resource value: 0x7f0500bb
			public const int login = 2131034299;
			
			// aapt resource value: 0x7f050081
			public const int mainscroll = 2131034241;
			
			// aapt resource value: 0x7f0500bc
			public const int menuItemLayouts = 2131034300;
			
			// aapt resource value: 0x7f050001
			public const int mini = 2131034113;
			
			// aapt resource value: 0x7f0500be
			public const int navheader_userimage = 2131034302;
			
			// aapt resource value: 0x7f050005
			public const int none = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int normal = 2131034114;
			
			// aapt resource value: 0x7f0500ba
			public const int password = 2131034298;
			
			// aapt resource value: 0x7f050097
			public const int progressBar1 = 2131034263;
			
			// aapt resource value: 0x7f05000d
			public const int pull_out = 2131034125;
			
			// aapt resource value: 0x7f0500e0
			public const int purseitemmainlayout = 2131034336;
			
			// aapt resource value: 0x7f0500d7
			public const int purseitemscroll = 2131034327;
			
			// aapt resource value: 0x7f050071
			public const int rAdd_Comission = 2131034225;
			
			// aapt resource value: 0x7f05006b
			public const int rSumm_Sent_Resent = 2131034219;
			
			// aapt resource value: 0x7f050069
			public const int rWithout_Comission = 2131034217;
			
			// aapt resource value: 0x7f05006d
			public const int radioGroup1 = 2131034221;
			
			// aapt resource value: 0x7f050076
			public const int radioGroup2 = 2131034230;
			
			// aapt resource value: 0x7f050096
			public const int relativeLayout1 = 2131034262;
			
			// aapt resource value: 0x7f050009
			public const int reveal = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int right = 2131034118;
			
			// aapt resource value: 0x7f050087
			public const int sBalance = 2131034247;
			
			// aapt resource value: 0x7f050018
			public const int sCategory = 2131034136;
			
			// aapt resource value: 0x7f050067
			public const int sContagent = 2131034215;
			
			// aapt resource value: 0x7f05008a
			public const int sEar = 2131034250;
			
			// aapt resource value: 0x7f050092
			public const int sEarning = 2131034258;
			
			// aapt resource value: 0x7f050093
			public const int sExpense = 2131034259;
			
			// aapt resource value: 0x7f050064
			public const int sFromPurse = 2131034212;
			
			// aapt resource value: 0x7f050094
			public const int sPrybutok = 2131034260;
			
			// aapt resource value: 0x7f050021
			public const int sPurse = 2131034145;
			
			// aapt resource value: 0x7f05008f
			public const int sSpus = 2131034255;
			
			// aapt resource value: 0x7f050066
			public const int sToPurse = 2131034214;
			
			// aapt resource value: 0x7f05008e
			public const int sVnes = 2131034254;
			
			// aapt resource value: 0x7f0500e1
			public const int spinnerItem = 2131034337;
			
			// aapt resource value: 0x7f05008d
			public const int sss = 2131034253;
			
			// aapt resource value: 0x7f050019
			public const int tAssetName = 2131034137;
			
			// aapt resource value: 0x7f0500db
			public const int tBalance = 2131034331;
			
			// aapt resource value: 0x7f050011
			public const int tBusinessName = 2131034129;
			
			// aapt resource value: 0x7f050029
			public const int tCategory = 2131034153;
			
			// aapt resource value: 0x7f05001d
			public const int tChecked = 2131034141;
			
			// aapt resource value: 0x7f050073
			public const int tChecked1 = 2131034227;
			
			// aapt resource value: 0x7f050079
			public const int tChecked2 = 2131034233;
			
			// aapt resource value: 0x7f05003f
			public const int tComment = 2131034175;
			
			// aapt resource value: 0x7f05003e
			public const int tContragent = 2131034174;
			
			// aapt resource value: 0x7f050060
			public const int tCreditor = 2131034208;
			
			// aapt resource value: 0x7f050023
			public const int tCurrency = 2131034147;
			
			// aapt resource value: 0x7f050030
			public const int tCurrent_price = 2131034160;
			
			// aapt resource value: 0x7f050015
			public const int tDate = 2131034133;
			
			// aapt resource value: 0x7f0500a6
			public const int tDateOkup = 2131034278;
			
			// aapt resource value: 0x7f050061
			public const int tDate_return = 2131034209;
			
			// aapt resource value: 0x7f05005f
			public const int tDate_start = 2131034207;
			
			// aapt resource value: 0x7f0500a2
			public const int tDayEar = 2131034274;
			
			// aapt resource value: 0x7f050017
			public const int tDescription = 2131034135;
			
			// aapt resource value: 0x7f0500de
			public const int tEarnings = 2131034334;
			
			// aapt resource value: 0x7f0500df
			public const int tExpence = 2131034335;
			
			// aapt resource value: 0x7f050033
			public const int tGain_on_sale = 2131034163;
			
			// aapt resource value: 0x7f05003d
			public const int tGroup = 2131034173;
			
			// aapt resource value: 0x7f0500c1
			public const int tHome = 2131034305;
			
			// aapt resource value: 0x7f0500a0
			public const int tHourEar = 2131034272;
			
			// aapt resource value: 0x7f0500a4
			public const int tMonthEar = 2131034276;
			
			// aapt resource value: 0x7f05002d
			public const int tName = 2131034157;
			
			// aapt resource value: 0x7f0500da
			public const int tNameCategoryPurse = 2131034330;
			
			// aapt resource value: 0x7f0500d9
			public const int tNamePurse = 2131034329;
			
			// aapt resource value: 0x7f050034
			public const int tPag = 2131034164;
			
			// aapt resource value: 0x7f0500ad
			public const int tPercent = 2131034285;
			
			// aapt resource value: 0x7f050016
			public const int tPrice = 2131034134;
			
			// aapt resource value: 0x7f050068
			public const int tPriceLayout = 2131034216;
			
			// aapt resource value: 0x7f0500af
			public const int tRemaining = 2131034287;
			
			// aapt resource value: 0x7f0500ae
			public const int tRemaining_summ = 2131034286;
			
			// aapt resource value: 0x7f050032
			public const int tSell_date = 2131034162;
			
			// aapt resource value: 0x7f050085
			public const int tStart = 2131034245;
			
			// aapt resource value: 0x7f0500ab
			public const int tSumm = 2131034283;
			
			// aapt resource value: 0x7f0500ac
			public const int tSumm_return = 2131034284;
			
			// aapt resource value: 0x7f0500a7
			public const int tTempOkup = 2131034279;
			
			// aapt resource value: 0x7f050086
			public const int tTime = 2131034246;
			
			// aapt resource value: 0x7f0500a5
			public const int tTimeOkup = 2131034277;
			
			// aapt resource value: 0x7f05003c
			public const int tTypeCat = 2131034172;
			
			// aapt resource value: 0x7f050040
			public const int tabHost1 = 2131034176;
			
			// aapt resource value: 0x7f0500b2
			public const int tabHost1Loans = 2131034290;
			
			// aapt resource value: 0x7f05009d
			public const int tableLayout1 = 2131034269;
			
			// aapt resource value: 0x7f050088
			public const int tableLayout2 = 2131034248;
			
			// aapt resource value: 0x7f05009e
			public const int tableRow1 = 2131034270;
			
			// aapt resource value: 0x7f0500a1
			public const int tableRow2 = 2131034273;
			
			// aapt resource value: 0x7f0500a3
			public const int tableRow3 = 2131034275;
			
			// aapt resource value: 0x7f050089
			public const int tableRow4 = 2131034249;
			
			// aapt resource value: 0x7f05008c
			public const int tableRow5 = 2131034252;
			
			// aapt resource value: 0x7f050090
			public const int tableRow6 = 2131034256;
			
			// aapt resource value: 0x7f050091
			public const int tableRow7 = 2131034257;
			
			// aapt resource value: 0x7f05008b
			public const int tableRow8 = 2131034251;
			
			// aapt resource value: 0x7f050099
			public const int tablescroll = 2131034265;
			
			// aapt resource value: 0x7f0500c4
			public const int tcashFlow = 2131034308;
			
			// aapt resource value: 0x7f0500dd
			public const int text1 = 2131034333;
			
			// aapt resource value: 0x7f0500dc
			public const int text2 = 2131034332;
			
			// aapt resource value: 0x7f0500e2
			public const int textNameTitle = 2131034338;
			
			// aapt resource value: 0x7f050050
			public const int textView1 = 2131034192;
			
			// aapt resource value: 0x7f050053
			public const int textView10 = 2131034195;
			
			// aapt resource value: 0x7f05009f
			public const int textView16 = 2131034271;
			
			// aapt resource value: 0x7f05009c
			public const int textView17 = 2131034268;
			
			// aapt resource value: 0x7f0500a8
			public const int textView18 = 2131034280;
			
			// aapt resource value: 0x7f050022
			public const int textView2 = 2131034146;
			
			// aapt resource value: 0x7f050020
			public const int textView3 = 2131034144;
			
			// aapt resource value: 0x7f050074
			public const int textView312141 = 2131034228;
			
			// aapt resource value: 0x7f05001e
			public const int textView3141 = 2131034142;
			
			// aapt resource value: 0x7f05007a
			public const int textView331141 = 2131034234;
			
			// aapt resource value: 0x7f050010
			public const int textView4 = 2131034128;
			
			// aapt resource value: 0x7f050065
			public const int textView455 = 2131034213;
			
			// aapt resource value: 0x7f050095
			public const int textView5 = 2131034261;
			
			// aapt resource value: 0x7f05001a
			public const int textView6 = 2131034138;
			
			// aapt resource value: 0x7f050024
			public const int textView7 = 2131034148;
			
			// aapt resource value: 0x7f0500ce
			public const int textView8 = 2131034318;
			
			// aapt resource value: 0x7f050052
			public const int textView9 = 2131034194;
			
			// aapt resource value: 0x7f0500e5
			public const int titleNameWithoutMenu = 2131034341;
			
			// aapt resource value: 0x7f05000b
			public const int top = 2131034123;
			
			// aapt resource value: 0x7f050062
			public const int tpercents = 2131034210;
			
			// aapt resource value: 0x7f050047
			public const int transferscroll = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int transfersmainlayout = 2131034184;
			
			// aapt resource value: 0x7f0500b9
			public const int userName = 2131034297;
			
			// aapt resource value: 0x7f050049
			public const int view1 = 2131034185;
			
			// aapt resource value: 0x7f0500d5
			public const int view10 = 2131034325;
			
			// aapt resource value: 0x7f05002a
			public const int view2 = 2131034154;
			
			// aapt resource value: 0x7f0500c5
			public const int view5 = 2131034309;
			
			// aapt resource value: 0x7f0500c8
			public const int view6 = 2131034312;
			
			// aapt resource value: 0x7f0500cb
			public const int view7 = 2131034315;
			
			// aapt resource value: 0x7f0500cf
			public const int view8 = 2131034319;
			
			// aapt resource value: 0x7f0500d2
			public const int view9 = 2131034322;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddBusinessLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AssetAddChangeCostLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AssetsAddItemLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AssetsItemLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AssetsLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AssetsMain = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int BillsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int BillsMain = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int BusinessLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int BusinessMain = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int CashFlowItemLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int CashFlowLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int CashFlowMain = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ContentLayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int DayMaxLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int DayMaxMain = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int GiveTakeLoanLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int InsertCashFlowLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int InsertLoansLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int InsertPurseLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int InvastmentItemLayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int InvestmentLayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int InvestmentMain = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int LoansItemLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int LoansLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int LoansMain = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int LoginLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Main = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int MenuItemLayout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int MenuLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int PurseItemLayout = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int PurseItems = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int SimpleSpinnerItem = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int TopWithMenuButton = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int TopWithoutMenu = 2130903074;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int Pop_upLoans = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int PopUp_Asset = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int PopUp_AssetItem = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int PopUp_Business = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int PopUp_Creditors = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int PopUp_debitors = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int PopUp_InvestItem = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int PopUp_menu = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int PopUp_Purse = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int PopUp_WithDelete = 2131296265;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f07004e
			public const int Accepted = 2131165262;
			
			// aapt resource value: 0x7f07007c
			public const int Active = 2131165308;
			
			// aapt resource value: 0x7f070030
			public const int Add = 2131165232;
			
			// aapt resource value: 0x7f07002b
			public const int Add_Asset = 2131165227;
			
			// aapt resource value: 0x7f070072
			public const int Add_Business = 2131165298;
			
			// aapt resource value: 0x7f07003a
			public const int Add_Comission = 2131165242;
			
			// aapt resource value: 0x7f07002d
			public const int Add_Purse = 2131165229;
			
			// aapt resource value: 0x7f07003f
			public const int All = 2131165247;
			
			// aapt resource value: 0x7f07005c
			public const int Anuitentic = 2131165276;
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070081
			public const int April = 2131165313;
			
			// aapt resource value: 0x7f070009
			public const int Assets = 2131165193;
			
			// aapt resource value: 0x7f070069
			public const int At_the_End = 2131165289;
			
			// aapt resource value: 0x7f070085
			public const int August = 2131165317;
			
			// aapt resource value: 0x7f07002c
			public const int Balance = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int Base_Currency = 2131165230;
			
			// aapt resource value: 0x7f07000c
			public const int Bills = 2131165196;
			
			// aapt resource value: 0x7f07003d
			public const int Borrow_More = 2131165245;
			
			// aapt resource value: 0x7f07000a
			public const int Business = 2131165194;
			
			// aapt resource value: 0x7f070048
			public const int Cancel = 2131165256;
			
			// aapt resource value: 0x7f070005
			public const int Capital = 2131165189;
			
			// aapt resource value: 0x7f07006c
			public const int Card_Number = 2131165292;
			
			// aapt resource value: 0x7f070007
			public const int CashFlow = 2131165191;
			
			// aapt resource value: 0x7f070017
			public const int Category = 2131165207;
			
			// aapt resource value: 0x7f070045
			public const int Change_Cost = 2131165253;
			
			// aapt resource value: 0x7f07004f
			public const int Commission = 2131165263;
			
			// aapt resource value: 0x7f07004c
			public const int CommissionToAccount = 2131165260;
			
			// aapt resource value: 0x7f070063
			public const int Complex = 2131165283;
			
			// aapt resource value: 0x7f070036
			public const int Conragent = 2131165238;
			
			// aapt resource value: 0x7f070057
			public const int Count_Month = 2131165271;
			
			// aapt resource value: 0x7f070042
			public const int Create_Purse = 2131165250;
			
			// aapt resource value: 0x7f07006d
			public const int Credit_Limit = 2131165293;
			
			// aapt resource value: 0x7f07001f
			public const int Creditor = 2131165215;
			
			// aapt resource value: 0x7f070041
			public const int Creditors = 2131165249;
			
			// aapt resource value: 0x7f07003b
			public const int Currency = 2131165243;
			
			// aapt resource value: 0x7f070027
			public const int Current_Price = 2131165223;
			
			// aapt resource value: 0x7f070013
			public const int Date = 2131165203;
			
			// aapt resource value: 0x7f070090
			public const int DateOkup = 2131165328;
			
			// aapt resource value: 0x7f070031
			public const int Date_Give = 2131165233;
			
			// aapt resource value: 0x7f070022
			public const int Date_Return = 2131165218;
			
			// aapt resource value: 0x7f070026
			public const int Date_Start = 2131165222;
			
			// aapt resource value: 0x7f070037
			public const int Date_Write = 2131165239;
			
			// aapt resource value: 0x7f07008c
			public const int DayEarning = 2131165324;
			
			// aapt resource value: 0x7f07009b
			public const int DayMax = 2131165339;
			
			// aapt resource value: 0x7f070092
			public const int Days = 2131165330;
			
			// aapt resource value: 0x7f070040
			public const int Debitors = 2131165248;
			
			// aapt resource value: 0x7f070089
			public const int December = 2131165321;
			
			// aapt resource value: 0x7f070052
			public const int Default = 2131165266;
			
			// aapt resource value: 0x7f07004b
			public const int Delete = 2131165259;
			
			// aapt resource value: 0x7f07001a
			public const int Description = 2131165210;
			
			// aapt resource value: 0x7f07005d
			public const int Difference = 2131165277;
			
			// aapt resource value: 0x7f07006b
			public const int Direction = 2131165291;
			
			// aapt resource value: 0x7f07004d
			public const int Discontinued = 2131165261;
			
			// aapt resource value: 0x7f070075
			public const int Ear = 2131165301;
			
			// aapt resource value: 0x7f07007a
			public const int Earning = 2131165306;
			
			// aapt resource value: 0x7f07000f
			public const int Earnings = 2131165199;
			
			// aapt resource value: 0x7f070053
			public const int Earnings_Purse = 2131165267;
			
			// aapt resource value: 0x7f070095
			public const int EditBalance = 2131165333;
			
			// aapt resource value: 0x7f070099
			public const int EndInvest = 2131165337;
			
			// aapt resource value: 0x7f070049
			public const int Error = 2131165257;
			
			// aapt resource value: 0x7f070064
			public const int Every_Day = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int Every_Month = 2131165285;
			
			// aapt resource value: 0x7f070068
			public const int Every_Year = 2131165288;
			
			// aapt resource value: 0x7f070077
			public const int Exp = 2131165303;
			
			// aapt resource value: 0x7f070054
			public const int Expences_Purse = 2131165268;
			
			// aapt resource value: 0x7f070010
			public const int Expenses = 2131165200;
			
			// aapt resource value: 0x7f070098
			public const int ExportData = 2131165336;
			
			// aapt resource value: 0x7f07007f
			public const int February = 2131165311;
			
			// aapt resource value: 0x7f070004
			public const int Financial_status = 2131165188;
			
			// aapt resource value: 0x7f070034
			public const int From_Purse = 2131165236;
			
			// aapt resource value: 0x7f070029
			public const int Gain_On_Sale = 2131165225;
			
			// aapt resource value: 0x7f070093
			public const int GiveEarning = 2131165331;
			
			// aapt resource value: 0x7f070094
			public const int GiveExpense = 2131165332;
			
			// aapt resource value: 0x7f07001d
			public const int Give_Loan = 2131165213;
			
			// aapt resource value: 0x7f07000e
			public const int History = 2131165198;
			
			// aapt resource value: 0x7f070006
			public const int Home = 2131165190;
			
			// aapt resource value: 0x7f07008b
			public const int HourEarning = 2131165323;
			
			// aapt resource value: 0x7f070055
			public const int House_Name = 2131165269;
			
			// aapt resource value: 0x7f070097
			public const int ImportData = 2131165335;
			
			// aapt resource value: 0x7f070014
			public const int Insert_Earnings = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int Insert_Expense = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int Insert_Transfer = 2131165206;
			
			// aapt resource value: 0x7f07006a
			public const int Institution = 2131165290;
			
			// aapt resource value: 0x7f07008a
			public const int InvestSettings = 2131165322;
			
			// aapt resource value: 0x7f07000b
			public const int Investment = 2131165195;
			
			// aapt resource value: 0x7f07007e
			public const int January = 2131165310;
			
			// aapt resource value: 0x7f070084
			public const int July = 2131165316;
			
			// aapt resource value: 0x7f070083
			public const int June = 2131165315;
			
			// aapt resource value: 0x7f070033
			public const int Loading = 2131165235;
			
			// aapt resource value: 0x7f070008
			public const int Loans = 2131165192;
			
			// aapt resource value: 0x7f070080
			public const int March = 2131165312;
			
			// aapt resource value: 0x7f070082
			public const int May = 2131165314;
			
			// aapt resource value: 0x7f07008d
			public const int MonthEarning = 2131165325;
			
			// aapt resource value: 0x7f070059
			public const int Month_Comission = 2131165273;
			
			// aapt resource value: 0x7f07001c
			public const int Name = 2131165212;
			
			// aapt resource value: 0x7f07005e
			public const int Name_Bank = 2131165278;
			
			// aapt resource value: 0x7f070071
			public const int Next_Month = 2131165297;
			
			// aapt resource value: 0x7f070088
			public const int November = 2131165320;
			
			// aapt resource value: 0x7f070047
			public const int OK = 2131165255;
			
			// aapt resource value: 0x7f070087
			public const int October = 2131165319;
			
			// aapt resource value: 0x7f07002a
			public const int Pag = 2131165226;
			
			// aapt resource value: 0x7f070046
			public const int Passive_Profit = 2131165254;
			
			// aapt resource value: 0x7f070058
			public const int Pay_Credit_Mounth = 2131165272;
			
			// aapt resource value: 0x7f07005a
			public const int Payment_Type = 2131165274;
			
			// aapt resource value: 0x7f070066
			public const int Per_Qartal = 2131165286;
			
			// aapt resource value: 0x7f070023
			public const int Percent = 2131165219;
			
			// aapt resource value: 0x7f07006f
			public const int Percent_Calculate = 2131165295;
			
			// aapt resource value: 0x7f07006e
			public const int Percent_Calculate_Every = 2131165294;
			
			// aapt resource value: 0x7f070061
			public const int Percent_Interval = 2131165281;
			
			// aapt resource value: 0x7f070060
			public const int Percent_Type = 2131165280;
			
			// aapt resource value: 0x7f07003c
			public const int Percents = 2131165244;
			
			// aapt resource value: 0x7f070012
			public const int Price = 2131165202;
			
			// aapt resource value: 0x7f07008e
			public const int PriceOkup = 2131165326;
			
			// aapt resource value: 0x7f070076
			public const int Pryb = 2131165302;
			
			// aapt resource value: 0x7f070018
			public const int Purse = 2131165208;
			
			// aapt resource value: 0x7f070044
			public const int Reg_Payment = 2131165252;
			
			// aapt resource value: 0x7f070025
			public const int Remaining = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int Remaining_Summ = 2131165220;
			
			// aapt resource value: 0x7f07003e
			public const int Return_Money = 2131165246;
			
			// aapt resource value: 0x7f070043
			public const int Sell_Asset = 2131165251;
			
			// aapt resource value: 0x7f070028
			public const int Sell_Date = 2131165224;
			
			// aapt resource value: 0x7f070086
			public const int September = 2131165318;
			
			// aapt resource value: 0x7f07009a
			public const int Settings = 2131165338;
			
			// aapt resource value: 0x7f070062
			public const int Simple = 2131165282;
			
			// aapt resource value: 0x7f070073
			public const int Start = 2131165299;
			
			// aapt resource value: 0x7f07005b
			public const int Start_Date = 2131165275;
			
			// aapt resource value: 0x7f07001b
			public const int Status = 2131165211;
			
			// aapt resource value: 0x7f07004a
			public const int Success = 2131165258;
			
			// aapt resource value: 0x7f070020
			public const int Summ = 2131165216;
			
			// aapt resource value: 0x7f070032
			public const int Summ_Loan = 2131165234;
			
			// aapt resource value: 0x7f070021
			public const int Summ_Return = 2131165217;
			
			// aapt resource value: 0x7f070039
			public const int Summ_Sent_Resent = 2131165241;
			
			// aapt resource value: 0x7f07007b
			public const int Summ_Spys = 2131165307;
			
			// aapt resource value: 0x7f07001e
			public const int Take_Loan = 2131165214;
			
			// aapt resource value: 0x7f070091
			public const int TempOkup = 2131165329;
			
			// aapt resource value: 0x7f070070
			public const int This_Month = 2131165296;
			
			// aapt resource value: 0x7f070074
			public const int Time = 2131165300;
			
			// aapt resource value: 0x7f07008f
			public const int TimeOkup = 2131165327;
			
			// aapt resource value: 0x7f070035
			public const int To_Purse = 2131165237;
			
			// aapt resource value: 0x7f070096
			public const int Transfer = 2131165334;
			
			// aapt resource value: 0x7f070050
			public const int Transfer_From = 2131165264;
			
			// aapt resource value: 0x7f07005f
			public const int Transfer_Money = 2131165279;
			
			// aapt resource value: 0x7f070051
			public const int Transfer_To = 2131165265;
			
			// aapt resource value: 0x7f070011
			public const int Transfers = 2131165201;
			
			// aapt resource value: 0x7f070067
			public const int Twice_Year = 2131165287;
			
			// aapt resource value: 0x7f070019
			public const int Type_Category = 2131165209;
			
			// aapt resource value: 0x7f07000d
			public const int UserName = 2131165197;
			
			// aapt resource value: 0x7f07007d
			public const int Vkladennya = 2131165309;
			
			// aapt resource value: 0x7f070078
			public const int Vnes = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int Vuv = 2131165305;
			
			// aapt resource value: 0x7f07002f
			public const int Withdraw = 2131165231;
			
			// aapt resource value: 0x7f070038
			public const int Without_Comission = 2131165240;
			
			// aapt resource value: 0x7f070056
			public const int Year_Percent = 2131165270;
			
			// aapt resource value: 0x7f070001
			public const int tab1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int tab2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int tab3 = 2131165187;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Splash = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CircleImageView = new int[] {
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int CircleImageView_civ_border_color = 1;
			
			// aapt resource value: 2
			public const int CircleImageView_civ_border_overlay = 2;
			
			// aapt resource value: 0
			public const int CircleImageView_civ_border_width = 0;
			
			// aapt resource value: 3
			public const int CircleImageView_civ_fill_color = 3;
			
			public static int[] FloatingActionButton = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] SwipeLayout = new int[] {
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000};
			
			// aapt resource value: 4
			public const int SwipeLayout_bottomEdgeSwipeOffset = 4;
			
			// aapt resource value: 6
			public const int SwipeLayout_clickToClose = 6;
			
			// aapt resource value: 0
			public const int SwipeLayout_drag_edge = 0;
			
			// aapt resource value: 1
			public const int SwipeLayout_leftEdgeSwipeOffset = 1;
			
			// aapt resource value: 2
			public const int SwipeLayout_rightEdgeSwipeOffset = 2;
			
			// aapt resource value: 5
			public const int SwipeLayout_show_mode = 5;
			
			// aapt resource value: 3
			public const int SwipeLayout_topEdgeSwipeOffset = 3;
			
			public static int[] SwipeListView = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 8
			public const int SwipeListView_swipeActionLeft = 8;
			
			// aapt resource value: 9
			public const int SwipeListView_swipeActionRight = 9;
			
			// aapt resource value: 1
			public const int SwipeListView_swipeAnimationTime = 1;
			
			// aapt resource value: 6
			public const int SwipeListView_swipeBackView = 6;
			
			// aapt resource value: 4
			public const int SwipeListView_swipeCloseAllItemsWhenMoveList = 4;
			
			// aapt resource value: 10
			public const int SwipeListView_swipeDrawableChecked = 10;
			
			// aapt resource value: 11
			public const int SwipeListView_swipeDrawableUnchecked = 11;
			
			// aapt resource value: 5
			public const int SwipeListView_swipeFrontView = 5;
			
			// aapt resource value: 7
			public const int SwipeListView_swipeMode = 7;
			
			// aapt resource value: 2
			public const int SwipeListView_swipeOffsetLeft = 2;
			
			// aapt resource value: 3
			public const int SwipeListView_swipeOffsetRight = 3;
			
			// aapt resource value: 0
			public const int SwipeListView_swipeOpenOnLongPress = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
